

# Site settings
title: Лабораторные работы
email: naveen@pixelblenders.com
#baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://naveenshaji.github.io/material" # the base hostname & protocol for your site
twitter_username: navvenshady
github_username:  naveenshaji
css: "cyan"
scroll-cursor: "#00BCD4"
scroll-rail: "#0097A7"

# Build settings
markdown: kramdown
highlighter: null #pygments
lsi: false
safe: false
